// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/error-visibility/MessageTooltip.tsx": () => import("../components/mockups/error-visibility/MessageTooltip.tsx"),
  "./components/mockups/error-visibility/SystemBanner.tsx": () => import("../components/mockups/error-visibility/SystemBanner.tsx"),
  "./components/mockups/error-visibility/WarningBanner.tsx": () => import("../components/mockups/error-visibility/WarningBanner.tsx")
};
